### ISSUE TITLE
Encountered an issue while running ‘log/pttltlog_comparison.ipynb’

### ISSUE THREAD

**Issue by xiao-qingjiang** [spttt/Per-FedAvg-APT#1]
When running log/pld_log-comparison.ipynb, there are NameErrors for "NameError: name' plot5figure-CICIIDS2017 'is not defined" and "NameError: name' plot1figure_dapt2020 'is not defined". How should we resolve this issue ?
<img width="587" alt="nameerror1" src="https://github.com/spttt/Per-FedAvg-APT/assets/60039329/2c7971ef-5c8b-42d2-99bf-5e3d354e4608">
<img width="482" alt="nameerror2" src="https://github.com/spttt/Per-FedAvg-APT/assets/60039329/ddce8570-240a-41bb-867b-03602dc25615">

**Comment by spttt** [comment]
I'm not sure the first cell in your picture ran successfully. The function is written in plot_utils.py. Please check the relative path.

**Comment by xiao-qingjiang** [comment]
Thank you very much for your answer. I have resolved this issue. Your work is excellent, thank you for providing the perfect code.
